### PR TITLE
Prettier

### LINKED ISSUE #13: Prettier config in the project

### PR DESCRIPTION
**Pull request by DeekshithRajBasa**
# Prettier - #13 

image
# Install Prettier by following the below steps:
#### and add the below config to  `.prettierrc`
`{
 printWidth: 120,
 singleQuote: true,
 useTabs: false,
 tabWidth: 2,
 semi: true,
 bracketSpacing: true
}`

#### Enable format on save if you wish to ✨, as It saves 2 valuable seconds.

`editor.formatOnSave: true`

## Tada 🙌, Happy coding ✌.

image

Credits: [Inspired from @victormejia's article](https://medium.com/@victormejia/setting-up-prettier-in-an-angular-cli-project-2f50c3b9a537)

### CODE REVIEW

**Comment by sardapv** [comment]
Thanks for PR. 😃

1.Add prettier ignore file too .. exclude unnecessary folders in it
2. Remove vs extension and test if works.
3. Add custom command in package.json

Ref : https://levelup.gitconnected.com/setup-prettier-on-angular-in-30-minutes-12b2ed85e7b7

**Review by sardapv — CHANGES_REQUESTED** [review]
Dropped overall changes to do on main conversation thread.

**Comment by DeekshithRajBasa** [comment]
> 1. Add prettier ignore file too .. exclude unnecessary folders in it
> 2. Remove vs extension and test if works.
> 3. Add custom command in package.json

@sardapv
1. I have added Prettier ignore `.prettierignore` file and it won't format unnecessary stuff 🙌
2. Well, yeah I have tested it on my machine and it is awesome 🤞
3. I have also added a custom command in scrips `npm run format` 💻. 

Tada 🙌✨, Prettier will format all the files within seconds 😁.

**Review by sardapv — APPROVED** [review]

**Comment by sardapv** [comment]
@all-contributors please add @DeekshithRajBasa  for code

**Comment by sardapv** [comment]
@all-contributors please add @DeekshithRajBasa for code

**Comment by sardapv** [comment]
@all-contributors please add @DeekshithRajBasa  for code, example

**Pull request merged**
